### ISSUE TITLE
Error in raw data proccessing

### ISSUE THREAD

**Issue by kunkun0w0** [zc-alexfan/arctic#27]
Hi! Thanks for releasing the code and dataset. I get a problem in data processing when using the command `python scripts_data/process_seqs.py --export_verts`. The error message is shown as follows:

```
Traceback (most recent call last):
  File "scripts_data/process_seqs.py", line 62, in main
    process_seq(task, export_verts=args.export_verts)
  File "./src/arctic/processing.py", line 448, in process_seq
    export_verts,
  File "./src/arctic/processing.py", line 90, in process_batch
    out_world = forward_gt_world(batch, layers, smplx_m)
  File "./src/arctic/processing.py", line 191, in forward_gt_world
    assert mano_l["joints.left"].shape[1] == 21
AssertionError
```

So how can I fix it? Thanks for your help!!

**Comment by zc-alexfan** [comment]
https://github.com/zc-alexfan/arctic/blob/master/docs/faq.md
