### ISSUE TITLE
Different dimensions of joints3d_r0 prediction and gt_model_joints_r while evaluating Arctic checkpoints

### ISSUE THREAD

**Issue by ruddradev** [zc-alexfan/arctic#47]
Hello,

While trying to evaluate the pretrained Arctic checkpoints, I encountered the following error. I was able to setup the code, environment and data according to the instructions given in the repository. [https://github.com/zc-alexfan/arctic/blob/master/docs/model/README.md](url)

When I ran the below command - 

`python scripts_method/extract_predicts.py --setup p1 --method arctic_sf --load_ckpt logs/3558f1342/checkpoints/last.ckpt --run_on val --extraction_mode eval_pose
`

I get the below error -

`
2024-07-26 12:24:05.734 | INFO     | __main__:main:93 - Processing seq s05/box_grab_01 1/34
2024-07-26 12:24:05.735 | INFO     | src.datasets.arctic_dataset:_load_data:307 - Loading ./data/arctic_data/data/splits/p2_val.npy
2024-07-26 12:24:06.522 | INFO     | src.datasets.tempo_inference_dataset:_load_data:51 - Loading ./data/arctic_data/data/feat/28bf3642f/p2_val.pt
2024-07-26 12:24:07.842 | INFO     | src.datasets.tempo_inference_dataset:__init__:92 - TempoInferDataset Loaded val split, num samples 660
  0%|                                                                                                                          | 0/1 [00:00<?, ?it/s]joints3d_r0 shape =  torch.Size([660, 21, 3])
gt_model_joints_r shape =  torch.Size([660, 16, 3])
  0%|                                                                                                                          | 0/1 [00:07<?, ?it/s]
Traceback (most recent call last):
  File "/home/ruddra/Ruddra/Code/arctic/scripts_method/extract_predicts.py", line 121, in <module>
    main()
  File "/home/ruddra/Ruddra/Code/arctic/scripts_method/extract_predicts.py", line 103, in main
    out_dict = wrapper.forward(inputs, targets, meta_info, "extract")
  File "/home/ruddra/Ruddra/Code/arctic/./src/models/generic/wrapper.py", line 115, in forward
    inputs, targets, meta_info = self.process_fn(
  File "/home/ruddra/Ruddra/Code/arctic/./src/callbacks/process/process_arctic.py", line 67, in process_data
    Tr0 = (joints3d_r0 - gt_model_joints_r).mean(dim=1)
RuntimeError: The size of tensor a (21) must match the size of tensor b (16) at non-singleton dimension 1
`

I printed the two variables to check whether the mismatch is because of them, and it was. Could it be a dataset issue or the way I set it up?

**Comment by zc-alexfan** [comment]
Your smplx package has only 16 joints instead of 21. See instructions here: https://github.com/zc-alexfan/arctic/blob/master/docs/setup.md

**Comment by ruddradev** [comment]
Thanks. This fix worked. I should have paid attention to this instruction.
